### ISSUE TITLE
You'd done a good job!

### ISSUE THREAD

**Issue by kamabokowen** [LTitan/Jkwx-Run#1]
Bro,I guess you're a student from CCU
which is also my school
I'm now in Grade one and thanks to your code
I passed my PE exam in last term.
I really hope you can continue to do this!

**Comment by LTitan** [comment]
hhh

**Comment by LTitan** [comment]
what is your name? hhhhh, I`d like to guess it.

**Comment by kamabokowen** [comment]
We shouldn't have known each other before.
If you like ,I'm honored that you can follow me on QQ 747103638

**Comment by inkedawn** [comment]
hhh. 
I am also a student at ccu, 
and I have written another library for the app
(neither c++ or python)

Do you want to make friends or do some communication with me?
